apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: collaborative-notes
data:
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_USER: postgres
  DB_NAME: collaborative_notes
  PORT: "8080"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: collaborative-notes
type: Opaque
data:
  db-password: cGFzc3dvcmQ= # base64 encoded "password"
  jwt-secret: eW91ci1zdXBlci1zZWNyZXQtand0LWtleQ== # base64 encoded "your-super-secret-jwt-key"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collaborative-notes-app
  namespace: collaborative-notes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: collaborative-notes-app
  template:
    metadata:
      labels:
        app: collaborative-notes-app
    spec:
      containers:
      - name: app
        image: collaborative-notes:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_USER
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_NAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: db-password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: jwt-secret
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PORT
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: collaborative-notes-service
  namespace: collaborative-notes
spec:
  selector:
    app: collaborative-notes-app
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
