apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-notes-frontend
  labels:
    app: cloud-notes-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-notes-frontend
  template:
    metadata:
      labels:
        app: cloud-notes-frontend
    spec:
      containers:
      - name: frontend
        image: cloud-notes-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          value: "http://cloud-notes-backend-service:8080"
        - name: REACT_APP_WS_URL
          value: "ws://cloud-notes-backend-service:8080/ws"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-notes-frontend-config
data:
  REACT_APP_API_URL: "http://cloud-notes-backend-service:8080"
  REACT_APP_WS_URL: "ws://cloud-notes-backend-service:8080/ws"